server1:
  build: ./
  ports:
    - "8080"

server2:
  build: ./
  ports:
    - "8080"

server3:
  build: ./
  ports:
    - "8080"

nginx:         # Build the 'server' image
  build: ./nginx     # Use the Dockerfile of the current directory
  links:
    - server1
    - server2
    - server3
  ports:        # Bind the port 80 of the host with
    - "80:80" # the port 8080 exposed by the container
